language: android
jdk: oraclejdk8

before_install:
  - yes | sdkmanager "platforms;android-30"

android:
  components:
    - tools
    - platform-tools
    - build-tools-30.0.2
    - android-30
    - extra

after_script:
    - cat app/build/reports/lint-results*.xml
