language: android
jdk: oraclejdk8

before_install:
  - yes | sdkmanager "platforms;android-30"
  - sudo apt-get update
  - sudo apt-get install -y mono-runtime

android:
  components:
    - tools
    - platform-tools
    - build-tools-29.0.3
    - android-30
    - extra

after_script:
    - cat app/build/reports/lint-results*.xml
